
export default [
  [
    "GuardianRank",
    "./definitions/GuardianRank.json"
  ],
  [
    "InventoryBucket",
    "./definitions/InventoryBucket.json"
  ],
  [
    "Artifact",
    "./definitions/Artifact.json"
  ],
  [
    "GuardianRankConstants",
    "./definitions/GuardianRankConstants.json"
  ],
  [
    "Class",
    "./definitions/Class.json"
  ],
  [
    "DamageType",
    "./definitions/DamageType.json"
  ],
  [
    "PowerCap",
    "./definitions/PowerCap.json"
  ],
  [
    "ItemTierType",
    "./definitions/ItemTierType.json"
  ],
  [
    "Gender",
    "./definitions/Gender.json"
  ],
  [
    "RewardSource",
    "./definitions/RewardSource.json"
  ],
  [
    "VendorGroup",
    "./definitions/VendorGroup.json"
  ],
  [
    "Race",
    "./definitions/Race.json"
  ],
  [
    "BreakerType",
    "./definitions/BreakerType.json"
  ],
  [
    "SocialCommendation",
    "./definitions/SocialCommendation.json"
  ],
  [
    "SocketCategory",
    "./definitions/SocketCategory.json"
  ],
  [
    "SeasonPass",
    "./definitions/SeasonPass.json"
  ],
  [
    "ReportReasonCategory",
    "./definitions/ReportReasonCategory.json"
  ],
  [
    "LoadoutConstants",
    "./definitions/LoadoutConstants.json"
  ],
  [
    "MedalTier",
    "./definitions/MedalTier.json"
  ],
  [
    "Place",
    "./definitions/Place.json"
  ],
  [
    "SocialCommendationNode",
    "./definitions/SocialCommendationNode.json"
  ],
  [
    "ActivityType",
    "./definitions/ActivityType.json"
  ],
  [
    "ActivityMode",
    "./definitions/ActivityMode.json"
  ],
  [
    "Stat",
    "./definitions/Stat.json"
  ],
  [
    "Season",
    "./definitions/Season.json"
  ],
  [
    "Trait",
    "./definitions/Trait.json"
  ],
  [
    "Faction",
    "./definitions/Faction.json"
  ],
  [
    "MaterialRequirementSet",
    "./definitions/MaterialRequirementSet.json"
  ],
  [
    "StatGroup",
    "./definitions/StatGroup.json"
  ],
  [
    "ItemCategory",
    "./definitions/ItemCategory.json"
  ],
  [
    "Destination",
    "./definitions/Destination.json"
  ],
  [
    "ActivityModifier",
    "./definitions/ActivityModifier.json"
  ],
  [
    "Milestone",
    "./definitions/Milestone.json"
  ],
  [
    "Metric",
    "./definitions/Metric.json"
  ],
  [
    "TalentGrid",
    "./definitions/TalentGrid.json"
  ],
  [
    "Location",
    "./definitions/Location.json"
  ],
  [
    "EventCard",
    "./definitions/EventCard.json"
  ],
  [
    "Progression",
    "./definitions/Progression.json"
  ],
  [
    "ProgressionMapping",
    "./definitions/ProgressionMapping.json"
  ],
  [
    "EnergyType",
    "./definitions/EnergyType.json"
  ],
  [
    "ProgressionLevelRequirement",
    "./definitions/ProgressionLevelRequirement.json"
  ],
  [
    "LoadoutName",
    "./definitions/LoadoutName.json"
  ],
  [
    "LoadoutIcon",
    "./definitions/LoadoutIcon.json"
  ],
  [
    "SocketType",
    "./definitions/SocketType.json"
  ],
  [
    "ActivityGraph",
    "./definitions/ActivityGraph.json"
  ],
  [
    "Checklist",
    "./definitions/Checklist.json"
  ],
  [
    "SandboxPerk",
    "./definitions/SandboxPerk.json"
  ],
  [
    "LoadoutColor",
    "./definitions/LoadoutColor.json"
  ],
  [
    "PresentationNode",
    "./definitions/PresentationNode.json"
  ],
  [
    "Activity",
    "./definitions/Activity.json"
  ],
  [
    "SandboxPattern",
    "./definitions/SandboxPattern.json"
  ],
  [
    "UnlockValue",
    "./definitions/UnlockValue.json"
  ],
  [
    "PlugSet",
    "./definitions/PlugSet.json"
  ],
  [
    "Record",
    "./definitions/Record.json"
  ],
  [
    "Collectible",
    "./definitions/Collectible.json"
  ],
  [
    "Lore",
    "./definitions/Lore.json"
  ],
  [
    "EquipmentSlot",
    "./definitions/EquipmentSlot.json"
  ],
  [
    "Objective",
    "./definitions/Objective.json"
  ],
  [
    "Vendor",
    "./definitions/Vendor.json"
  ],
  [
    "InventoryItemLite",
    "./definitions/InventoryItemLite.json"
  ],
  [
    "Unlock",
    "./definitions/Unlock.json"
  ],
  [
    "InventoryItem",
    "./definitions/InventoryItem.json"
  ]
];
export const manifestVersion = "119016.23.09.18.1805-1-bnet.52208__en";
